const drawResults = {
    "2KfZhdmK": "2LPZhtiv2LM=",
    "2YbZiNix2Kk=": "2LPZgdin2YbYpw==",
    "2KfZhdmE": "2YXZhtmJ",
    "2YfZhtiv": "2LTZh9iv",
    "2YXZhtmJ": "2KfZhdmE",
    "2KfZitmF2KfZhg==": "2LPZhNin2YE=",
    "2YbZiNix2Yo=": "2K/Zitin2YTYpw==",
    "2LTZh9iv": "2YbZiNix2Yo=",
    "2LTZitmF2KfYoQ==": "2LHZitmG2KfYrw==",
    "2LPZhtiv2LM=": "2LTZitmF2KfYoQ==",
    "2LHZitmG2KfYrw==": "2YbZiNmB",
    "2YbZiNmB": "2KfZitmF2KfZhg==",
    "2LPZhNin2YE=": "2LPYp9ix2Kc=",
    "2LPZgdin2YbYpw==": "2YfZhtiv",
    "2LPYp9ix2Kc=": "2YbZiNix2Kk=",
    "2K/Zitin2YTYpw==": "2KfZhdmK",
    "2KrYsdmB": "2YbYrNmI2K8=",
    "2YbYrNmI2K8=": "2KrYsdmB",
    "2YrZiNiz2YE=": "2YbZiNin2YE=",
    "2YbZiNin2YE=": "2YrZiNiz2YE="
};